CREATE TABLE IF NOT EXISTS `4473_queue` (
  `cid` VARCHAR(50) NOT NULL,
  `store` VARCHAR(50) DEFAULT NULL,
  `weaponname` VARCHAR(50) DEFAULT NULL,
  `date` VARCHAR(175) DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`cid`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS `4473_errorcount` (
  `cid` VARCHAR(50) NOT NULL,
  `errors` INT(10) DEFAULT NULL,
  PRIMARY KEY (`cid`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS `4473_purchasehistory` (
  `purchaseid` VARCHAR(50) NOT NULL,
  `main` VARCHAR(255) DEFAULT NULL,
  `data` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`purchaseid`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1;




